# Generated by Django 4.2.5 on 2023-09-16 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0002_carrito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='name',
        ),
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ItemCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_item', models.IntegerField(default=1)),
                ('carrito_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signals.carrito')),
                ('producto_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signals.producto')),
            ],
        ),
        migrations.AddField(
            model_name='carrito',
            name='items',
            field=models.ManyToManyField(through='signals.ItemCarrito', to='signals.producto'),
        ),
    ]
